// SPDX-FileCopyrightText: 2021 Visne <39844191+Visne@users.noreply.github.com>
// SPDX-FileCopyrightText: 2021 metalgearsloth <comedian_vs_clown@hotmail.com>
// SPDX-FileCopyrightText: 2021 moonheart08 <moonheart08@users.noreply.github.com>
// SPDX-FileCopyrightText: 2022 Paul Ritter <ritter.paul1@googlemail.com>
// SPDX-FileCopyrightText: 2022 Rinkashikachi <15rinkashikachi15@gmail.com>
// SPDX-FileCopyrightText: 2022 mirrorcult <lunarautomaton6@gmail.com>
// SPDX-FileCopyrightText: 2022 wrexbe <81056464+wrexbe@users.noreply.github.com>
// SPDX-FileCopyrightText: 2023 Morb <14136326+Morb0@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 Aiden <28298836+Aidenkrz@users.noreply.github.com>
//
// SPDX-License-Identifier: MIT

using System.Linq;
using Content.Shared._CorvaxGoob.CCCVars;
using Content.Shared._CorvaxGoob.TTS;
using Content.Shared.Administration;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Audio.Systems;
using Robust.Shared.Configuration;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client.Administration.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class AdminAnnounceWindow : DefaultWindow
    {
        [Dependency] private readonly ILocalizationManager _localization = default!;
        [Dependency] private readonly IEntitySystemManager _sysMan = default!; // RS14
        [Dependency] private readonly IConfigurationManager _cfgManager = default!; // CorvaxGoob-TTS
        [Dependency] private readonly IPrototypeManager _prototypeManager = default!; // CorvaxGoob-TTS
        // RS14-start
        private AdminAnnounceColorPalette? _paletteWindow;
        private SharedAudioSystem? _audio;
        private EntityUid? _previewStream;
        // RS14-end
        private List<TTSVoicePrototype> _voiceList = new(); // CorvaxGoob-TTS

        public AdminAnnounceWindow()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);
            // RS14-start
            _audio = _sysMan.GetEntitySystem<SharedAudioSystem>();

            SoundPath.Text = AdminAnnounceDefaults.DefaultSoundPath;

            Announcement.Placeholder =
                new Rope.Leaf(_localization.GetString("admin-announce-announcement-placeholder"));

            InitAnnounceMethods();

            EnableSender.OnToggled += _ => UpdateSenderEditable();
            PlayAudio.OnPressed += _ => TogglePreview();
            OpenPaletteButton.OnPressed += _ => OpenPalette();
            Announcement.OnTextChanged += _ => UpdateButtons();
            AnnounceButton.OnPressed += _ =>
            {
                StopPreview();
                UpdateButtons();
            };
            // RS14-end
            // CorvaxGoob-TTS-Start
            if (_cfgManager.GetCVar(CCCVars.TTSEnabled))
            {
                TTSContainer.Visible = true;
                InitializeVoice();
            }
            // CorvaxGoob-TTS-End
            UpdateSenderEditable(); // RS14
        }

        // CorvaxGoob-TTS-Start
        private void InitializeVoice()
        {
            _voiceList = _prototypeManager
                .EnumeratePrototypes<TTSVoicePrototype>()
                .OrderBy(o => Loc.GetString(o.Name))
            .ToList();

            VoiceButton.AddItem(Loc.GetString("tts-voice-none"));
            VoiceButton.SetItemMetadata(0, "None");

            for (var i = 1; i < _voiceList.Count; i++)
            {
                var name = Loc.GetString(_voiceList[i].Name);
                VoiceButton.AddItem(name);
                VoiceButton.SetItemMetadata(i, _voiceList[i].ID);
            }

            VoiceButton.OnItemSelected += args => { VoiceButton.SelectId(args.Id); }; // RS14
        }
        // CorvaxGoob-TTS-End
        // RS14-start
        private void UpdateSenderEditable()
        {
            Sender.Editable = EnableSender.Pressed;
        }

        private void InitAnnounceMethods()
        {
            AnnounceMethod.AddItem(_localization.GetString("admin-announce-type-station"));
            AnnounceMethod.SetItemMetadata(0, AdminAnnounceType.Station);
            AnnounceMethod.AddItem(_localization.GetString("admin-announce-type-server"));
            AnnounceMethod.SetItemMetadata(1, AdminAnnounceType.Server);
            AnnounceMethod.OnItemSelected += args =>
            {
                AnnounceMethod.SelectId(args.Id);
                UpdateFields((AdminAnnounceType?)args.Button.SelectedMetadata ?? AdminAnnounceType.Station);
            };

            AnnounceMethod.SelectId(0);
            UpdateFields(AdminAnnounceType.Station);
        }

        private void UpdateFields(AdminAnnounceType type)
        {
            var isStation = type == AdminAnnounceType.Station;
            Announcer.Editable = SoundPath.Editable = isStation;
            EnableSender.Visible = isStation;
            Sender.Editable = isStation && EnableSender.Pressed;
            GlobalAnnouncement.Visible = isStation;

            // CorvaxGoob-TTS
            TTSContainer.Visible = _cfgManager.GetCVar(CCCVars.TTSEnabled) && isStation;

            _currentHex = AdminAnnounceDefaults.GetDefaultColorHex(type);

            OnColorChanged();

            if (!isStation)
                StopPreview();

            UpdateButtons();
        }

        public override void Close()
        {
            base.Close();

            _paletteWindow?.Close();

            StopPreview();
        } 
        // RS14-end
    }
}