# Underwear
- type: loadout
  id: UnderwearBottomBoxersHeadOfSecurity
  effects:
  - !type:GroupLoadoutEffect
    proto: MaleUnderwear
  equipment:
    underwearb: ClothingUnderwearBottomBoxersHeadOfSecurity

- type: loadout
  id: UnderwearBottomPantiesHeadOfSecurity
  effects:
  - !type:GroupLoadoutEffect
    proto: FemaleUnderwear
  equipment:
    underwearb: ClothingUnderwearBottomPantiesHeadOfSecurity

- type: loadout
  id: UnderwearTopBraHeadOfSecurity
  effects:
  - !type:GroupLoadoutEffect
    proto: FemaleUnderwear
  equipment:
    underweart: ClothingUnderwearTopBraHeadOfSecurity
