- type: job
  id: NanotrasenCareerTrainer
  name: job-name-nct
  description: job-description-nct
  playTimeTracker: JobNanotrasenCareerTrainer
  #goobcoins: 45 Corvax-Goob-coins
  weight: 20
  startingGear: NanotrasenCareerTrainerGear
  icon: "JobIconNanotrasenTrainer"
  joinNotifyCrew: true
  supervisors: job-supervisors-ntr-centcom
  canBeAntag: false
  whitelisted: true
  setPreference: true # RS14-value: false -> true
  skills: # RS14
  - Cooking
  - Drinks
  - Hydroponics
  - Butchering
  - Medical
  - Pharmacology
  - Chemistry
  - Stasis
  - Virology
  - Surgery
  - Engineering
  - Construction
  - Atmos
  - Engines
  - AdvancedEngines
  - Supermatter
  - Piloting
  - Detective
  - Shooting
  - Xenobiology
  - Exosuits
  - Robotics
  - Anomaly
  - Artifacts
  - PlantMutation
  - Magic
  # RS14-start
  access:
  - NanotrasenCareerTrainer
  - External
  - Cryogenics
  - Brig
  - Lawyer
  - Engineering
  - Maintenance
  - Medical
  - Research
  - Cargo
  - Theatre
  - CentralCommand
  - NanotrasenRepresentative
  # RS14-end
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, BluespaceLifelineImplant ]
#  - !type:AddComponentSpecial # Intentionally not command. I don't want them to ruin rev rounds.
#    components:
#    - type: CommandStaff

- type: startingGear
  id: NanotrasenCareerTrainerGear
  equipment:
    id: TrainerPDA
    ears: ClothingHeadsetAltCentCom
    eyes: ClothingEyesGlassesCentComm
    pocket1: UniqueNanotrasenCareerTrainerLockerTeleporter # RS14
    pocket2: WeaponDisabler # RS14-value: FoodSnackLollypopWrappedCentComm -> WeaponDisabler
  storage:
    back:
    - Flash
    - TelescopicBatonAdvanced
    - CentralCommandBusinessCard
    - FoodSnackLollypopWrappedCentComm # RS14

- type: chameleonOutfit
  id: NanotrasenCareerTrainerChameleonOutfit
  job: NanotrasenCareerTrainer
  equipment:
    eyes: ClothingEyesGlassesCentComm
    mask: ClothingMaskBreath
    ears: ClothingHeadsetAltCentCom
    gloves: ClothingHandsGlovesHeavyGoldenTrim
    jumpsuit: ClothingUniformJumpsuitTrainer
    id: TrainerPDA
    back: ClothingBackpackSatchelLeather
    shoes: ClothingShoesBootsLaceup
    outerClothing: ClothingOuterWinterCoatTrainer
    head: ClothingHeadHatTrainer
    neck: ClothingNeckChameleon
