// SPDX-FileCopyrightText: 2024 Piras314 <p1r4s@proton.me>
// SPDX-FileCopyrightText: 2024 iNVERTED <alextjorgensen@gmail.com>
// SPDX-FileCopyrightText: 2024 metalgearsloth <31366439+metalgearsloth@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 Aiden <28298836+Aidenkrz@users.noreply.github.com>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Shared._RedStar.Audio.Jukebox;
using Content.Shared.Audio.Jukebox;
using Robust.Client.Audio;
using Robust.Client.AutoGenerated;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Audio.Components;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using FancyWindow = Content.Client.UserInterface.Controls.FancyWindow;

namespace Content.Client.Audio.Jukebox;

[GenerateTypedNameReferences]
public sealed partial class JukeboxMenu : FancyWindow
{
    [Dependency] private readonly IEntityManager _entManager = default!;
    [Dependency] private readonly IResourceCache _resourceCache = default!; // RS14
    private AudioSystem _audioSystem;
    private JukeboxSystem _jukeboxSystem; // RS14
    private readonly List<JukeboxPrototype> _allSongs = new(); // RS14

    /// <summary>
    /// Are we currently 'playing' or paused for the play / pause button.
    /// </summary>
    private bool _playState;
    private bool _updatingSongList; // RS14
    private ProtoId<JukeboxPrototype>? _selectedSongId; // RS14

    /// <summary>
    /// True if playing, false if paused.
    /// </summary>
    public event Action<bool>? OnPlayPressed;
    // RS14-start
    public event Action? OnNextPressed;
    public event Action? OnPreviousPressed;
    public event Action<bool>? OnShuffleToggled;
    public event Action<bool>? OnRepeatToggled;
    // RS14-end
    public event Action<ProtoId<JukeboxPrototype>>? OnSongSelected;
    public event Action<float>? SetTime;
    public event Action<float>? SetVolume; // RS14

    private EntityUid _jukebox; // RS14
    private EntityUid? _audio;

    private float _lockTimer;
    // RS14-start
    private float _volume = JukeboxVolume.DefaultValue;
    private float _lastSentVolume = JukeboxVolume.DefaultValue;
    private float _volumeSendAccumulator;
    private const float VolumeSendInterval = 0.12f;
    private const float VolumeSendTolerance = 0.01f;
    private const string PlayIconTexturePath = "/Textures/Interface/AdminActions/play.png";
    private const string PauseIconTexturePath = "/Textures/Interface/AdminActions/pause.png";
    private const string VolumeIconRsiPath = "/Textures/Interface/Actions/actions_borg.rsi";
    private const string VolumeIconState = "musical-module";
    // RS14-end

    public JukeboxMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _audioSystem = _entManager.System<AudioSystem>();
        // RS14-start
        _jukeboxSystem = _entManager.System<JukeboxSystem>();
        SetVolumeIcon();
        VolumeSlider.MinValue = JukeboxVolume.MinValue;
        VolumeSlider.MaxValue = JukeboxVolume.MaxValue;
        VolumeSlider.Page = 0f;
        // RS14-end
        MusicList.OnItemSelected += args =>
        {
            // RS14-start
            if (_updatingSongList)
                return;
            // RS14-end
            var entry = MusicList[args.ItemIndex];

            if (entry.Metadata is not string juke)
                return;

            OnSongSelected?.Invoke(juke);
        };

        PlayButton.OnPressed += args =>
        {
            OnPlayPressed?.Invoke(!_playState);
        };
        // RS14-start
        PreviousButton.OnPressed += _ => OnPreviousPressed?.Invoke();
        NextButton.OnPressed += _ => OnNextPressed?.Invoke();
        ShuffleButton.OnToggled += args => OnShuffleToggled?.Invoke(args.Pressed);
        RepeatButton.OnToggled += args => OnRepeatToggled?.Invoke(args.Pressed);
        SearchInput.OnTextChanged += _ => RefreshSongList();
        PlaybackSlider.OnReleased += PlaybackSliderKeyUp;
        VolumeSlider.OnValueChanged += _ => OnVolumeSliderChanged();

        SetPlayPauseButton(_audioSystem.IsPlaying(_audio), force: true);
        SetVolumeSlider(_volume, force: true);
        // RS14-end
    }
    // RS14-start
    public void SetJukebox(EntityUid jukebox)
    {
        _jukebox = jukebox;

        if (!_jukeboxSystem.TryGetVolumeOverride(jukebox, out var volume))
            return;

        SetVolumeSlider(volume, force: true);
    }
    // RS14-end
    public void SetAudioStream(EntityUid? audio)
    {
        _audio = audio;
        // RS14-start
        TryApplyLocalVolume(_volume);
        // RS14-end
    }

    private void PlaybackSliderKeyUp(Slider args)
    {
        SetTime?.Invoke(PlaybackSlider.Value);
        _lockTimer = 0.5f;
    }

    /// <summary>
    /// Re-populates the list of jukebox prototypes available.
    /// </summary>
    public void Populate(IEnumerable<JukeboxPrototype> jukeboxProtos)
    {
        // RS14-start
        _allSongs.Clear();
        _allSongs.AddRange(jukeboxProtos);
        _allSongs.Sort(static (left, right) => string.Compare(left.Name, right.Name, StringComparison.OrdinalIgnoreCase));
        RefreshSongList();
        // RS14-end
    }

    public void SetPlayPauseButton(bool playing, bool force = false)
    {
        if (_playState == playing && !force)
            return;

        _playState = playing;

        if (playing)
        {
            // RS14-start
            PlayIcon.TexturePath = PauseIconTexturePath;
            PlayButton.ToolTip = Loc.GetString("jukebox-menu-buttonpause");
            // RS14-end
            return;
        }
        // RS14-start
        PlayIcon.TexturePath = PlayIconTexturePath;
        PlayButton.ToolTip = Loc.GetString("jukebox-menu-buttonplay");
        // RS14-end
    }
    // RS14-start
    public void SetSelectedSong(ProtoId<JukeboxPrototype>? songId, string? name, float length)
    {
        var resetSlider = _selectedSongId != songId || Math.Abs(PlaybackSlider.MaxValue - length) > 0.05f;
        _selectedSongId = songId;
        SetSelectedSongText(name);
        PlaybackSlider.MaxValue = length;

        if (resetSlider)
            PlaybackSlider.SetValueWithoutEvent(0);

        RefreshSelection();
    }

    public void SetShuffleEnabled(bool enabled)
    {
        ShuffleButton.Pressed = enabled;
    }

    public void SetRepeatEnabled(bool enabled)
    {
        RepeatButton.Pressed = enabled;
    }

    public void SetVolumeSlider(float volume, bool force = false)
    {
        volume = JukeboxVolume.Clamp(volume);

        if (!force && Math.Abs(_volume - volume) <= VolumeSendTolerance)
            return;

        _volume = volume;
        var sliderValue = 1f - volume;
        VolumeSlider.ValueTarget = sliderValue;
        VolumeSlider.SetValueWithoutEvent(sliderValue);
        UpdateVolumeLabel();
        TryApplyLocalVolume(volume);
    }

    private void SetVolumeIcon()
    {
        var rsi = _resourceCache.GetResource<RSIResource>(VolumeIconRsiPath).RSI;

        if (rsi.TryGetState(VolumeIconState, out var state))
            VolumeIcon.Texture = state.Frame0;
    }
    // RS14-end
    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (_lockTimer > 0f)
        {
            _lockTimer -= args.DeltaSeconds;
        }
        // RS14-start
        if (_volumeSendAccumulator > 0f)
        {
            _volumeSendAccumulator -= args.DeltaSeconds;
            if (_volumeSendAccumulator <= 0f)
            {
                FlushPendingVolume();
            }
        }
        // RS14-end
        PlaybackSlider.Disabled = _lockTimer > 0f;

        if (_entManager.TryGetComponent(_audio, out AudioComponent? audio))
        {
            DurationLabel.Text = $@"{TimeSpan.FromSeconds(audio.PlaybackPosition):mm\:ss} / {_audioSystem.GetAudioLength(audio.FileName):mm\:ss}";
        }
        else
        {
            DurationLabel.Text = $@"00:00 / {TimeSpan.FromSeconds(PlaybackSlider.MaxValue):mm\:ss}"; // RS14
        }

        if (PlaybackSlider.Grabbed)
            return;

        if (audio != null || _entManager.TryGetComponent(_audio, out audio))
        {
            PlaybackSlider.SetValueWithoutEvent(audio.PlaybackPosition);
        }
        else
        {
            PlaybackSlider.SetValueWithoutEvent(0f);
        }

        SetPlayPauseButton(_audioSystem.IsPlaying(_audio, audio));
    }

    public void SetSelectedSongText(string? text)
    {
        if (!string.IsNullOrEmpty(text))
        {
            SongName.Text = text;
        }
        else
        {
            SongName.Text = "---";
        }
    }
    // RS14-start
    public bool TryGetLocalVolumeOverride(out float volume)
    {
        volume = _volume;
        return true;
    }

    public void CommitVolumeState()
    {
        if (_volumeSendAccumulator > 0f)
            FlushPendingVolume();

        _jukeboxSystem.SetVolumeOverride(_jukebox, _volume);
    }

    private void RefreshSongList()
    {
        _updatingSongList = true;
        MusicList.Clear();

        var filter = SearchInput.Text.Trim();
        foreach (var song in _allSongs)
        {
            if (!string.IsNullOrEmpty(filter) &&
                !song.Name.Contains(filter, StringComparison.OrdinalIgnoreCase) &&
                !song.ID.Contains(filter, StringComparison.OrdinalIgnoreCase))
            {
                continue;
            }

            var item = MusicList.AddItem(song.Name, metadata: song.ID);
            item.Selected = _selectedSongId == song.ID;
        }

        _updatingSongList = false;
    }

    private void RefreshSelection()
    {
        _updatingSongList = true;
        foreach (var item in MusicList)
        {
            item.Selected = item.Metadata is string songId && _selectedSongId == songId;
        }

        _updatingSongList = false;
    }

    private void OnVolumeSliderChanged()
    {
        _volume = JukeboxVolume.Clamp(1f - VolumeSlider.Value);
        _jukeboxSystem.SetVolumeOverride(_jukebox, _volume);
        UpdateVolumeLabel();
        TryApplyLocalVolume(_volume);

        if (Math.Abs(_volume - _lastSentVolume) <= VolumeSendTolerance)
            return;

        _volumeSendAccumulator = VolumeSendInterval;
    }

    private void FlushPendingVolume()
    {
        _volumeSendAccumulator = 0f;

        if (Math.Abs(_volume - _lastSentVolume) <= VolumeSendTolerance)
            return;

        _lastSentVolume = _volume;
        SetVolume?.Invoke(_volume);
    }

    private void UpdateVolumeLabel()
    {
        VolumeValueLabel.Text = $"{(int) MathF.Round(_volume * 100f)}%";
    }

    private void TryApplyLocalVolume(float volume)
    {
        _jukeboxSystem.ApplyClientVolume(_audio, volume);
    }
    // RS14-end
}