// SPDX-FileCopyrightText: 2026 RedStar Contributors
//
// SPDX-License-Identifier: MIT

using Content.Shared.Mech;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Mech.Ui.Equipment;

[GenerateTypedNameReferences]
public sealed partial class MechGeneratorUiFragment : BoxContainer
{
    public event Action? OnEjectFuelAction;

    public MechGeneratorUiFragment()
    {
        RobustXamlLoader.Load(this);
        EjectFuelButton.OnPressed += _ => OnEjectFuelAction?.Invoke();
    }

    public void UpdateContents(MechGeneratorUiState state)
    {
        OutputLabel.Text = Loc.GetString("mech-generator-output-label",
            ("rate", $"{state.ChargeCurrent:F0}/{state.ChargeMax:F0}"));

        FuelLabel.Visible = state.HasFuel;
        EjectFuelButton.Visible = state.HasFuel;

        if (!state.HasFuel)
            return;

        FuelLabel.Text = Loc.GetString("mech-generator-fuel-label",
            ("name", state.FuelName ?? string.Empty),
            ("amount", $"{state.FuelAmount:F0}/{state.FuelCapacity:F0}"));
    }
}
