- type: latheRecipe
  parent: BaseWeaponRecipeLong
  id: WeaponEnergyCrossbowLarge
  result: WeaponEnergyCrossbowLarge
  materials:
    Steel: 3500
    Glass: 100
    Plastic: 1500
    Gold: 1000
    RSCrystal: 200