// SPDX-FileCopyrightText: 2023 DrSmugleaf <DrSmugleaf@users.noreply.github.com>
// SPDX-FileCopyrightText: 2023 Visne <39844191+Visne@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 Nemanja <98561806+EmoGarbage404@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 Piras314 <p1r4s@proton.me>
// SPDX-FileCopyrightText: 2024 deltanedas <39013340+deltanedas@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 deltanedas <@deltanedas:kde.org>
// SPDX-FileCopyrightText: 2024 metalgearsloth <31366439+metalgearsloth@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 themias <89101928+themias@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 Aiden <28298836+Aidenkrz@users.noreply.github.com>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Client.UserInterface.Fragments;
using Content.Shared.Mech;
using Content.Shared.Mech.Components;
using Content.Shared.Mech.Module.Components;
using Content.Shared.Temperature;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Mech.Ui;

[GenerateTypedNameReferences]
public sealed partial class MechMenu : FancyWindow
{
    [Dependency] private readonly IEntityManager _ent = default!;

    private EntityUid _mech;
    private BoundUserInterface? _parentBui;

    public event Action<EntityUid>? OnRemoveEquipmentButtonPressed;
    // RS14-start
    public event Action<EntityUid>? OnRemoveModuleButtonPressed;
    public event Action? OnDnaLockRegister;
    public event Action? OnDnaLockToggle;
    public event Action? OnDnaLockReset;
    public event Action? OnCardLockRegister;
    public event Action? OnCardLockToggle;
    public event Action? OnCardLockReset;
    public event Action? OnCabinPurge;
    public event Action<bool>? OnAirtightToggle;
    public event Action<bool>? OnFanToggle;
    public event Action<bool>? OnFilterToggle;
    // RS14-end

    public MechMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        // RS14-start
        DnaLockRegisterButton.OnPressed += _ => OnDnaLockRegister?.Invoke();
        DnaLockToggleButton.OnPressed += _ => OnDnaLockToggle?.Invoke();
        DnaLockResetButton.OnPressed += _ => OnDnaLockReset?.Invoke();
        CardLockRegisterButton.OnPressed += _ => OnCardLockRegister?.Invoke();
        CardLockToggleButton.OnPressed += _ => OnCardLockToggle?.Invoke();
        CardLockResetButton.OnPressed += _ => OnCardLockReset?.Invoke();
        CabinPurgeButton.OnPressed += _ => OnCabinPurge?.Invoke();
        AirtightToggleButton.OnPressed += args => OnAirtightToggle?.Invoke(args.Button.Pressed);
        FanToggleButton.OnPressed += args => OnFanToggle?.Invoke(args.Button.Pressed);
        FilterToggleButton.OnPressed += args => OnFilterToggle?.Invoke(args.Button.Pressed);
        // RS14-end
    }

    public void SetEntity(EntityUid uid)
    {
        MechView.SetEntity(uid);
        _mech = uid;
    }

    public void SetParentBui(BoundUserInterface parentBui)
    {
        _parentBui = parentBui;
    }

    public void UpdateMechStats(MechBoundUiState state)
    {
        var integrityPercent = state.MaxIntegrity > 0f
            ? state.Integrity / state.MaxIntegrity
            : 0f;
        IntegrityDisplayBar.Value = integrityPercent;
        IntegrityDisplay.Text = Loc.GetString(state.IsBroken
            ? "mech-integrity-display-broken"
            : "mech-integrity-display", ("amount", (int) (integrityPercent * 100)));

        if (state.MaxEnergy > 0f)
        {
            var energyPercent = state.Energy / state.MaxEnergy;
            EnergyDisplayBar.Value = energyPercent;
            EnergyDisplay.Text = Loc.GetString("mech-energy-display", ("amount", (int) (energyPercent * 100)));
        }
        else
        {
            EnergyDisplayBar.Value = 0f;
            EnergyDisplay.Text = Loc.GetString("mech-energy-missing");
        }

        SlotDisplay.Text = Loc.GetString("mech-equipment-slot-display-label",
            ("used", state.EquipmentUsed),
            ("max", state.MaxEquipmentAmount));

        ModuleSlotDisplay.Text = Loc.GetString("mech-module-slot-display-label",
            ("used", state.ModuleSpaceUsed),
            ("max", state.ModuleSpaceMax));

        UpdateLockControls(state);
        UpdateCabinControls(state);
    }

    public void UpdateEquipmentView(IReadOnlyList<NetEntity> equipment, IReadOnlyList<NetEntity> modules)
    {
        if (!ContainerMatches(EquipmentControlContainer, equipment))
            RebuildEquipmentView(equipment);

        if (!ContainerMatches(ModuleControlContainer, modules))
            RebuildModuleView(modules);
    }

    private void RebuildEquipmentView(IReadOnlyList<NetEntity> equipment)
    {
        EquipmentControlContainer.Children.Clear();
        foreach (var netEnt in equipment)
        {
            var ent = _ent.GetEntity(netEnt);
            var control = CreateEquipmentControl(ent);
            if (control == null)
                continue;

            control.OnRemoveButtonPressed += () => OnRemoveEquipmentButtonPressed?.Invoke(ent);
            EquipmentControlContainer.AddChild(control);
        }
    }

    // RS14-start
    private void RebuildModuleView(IReadOnlyList<NetEntity> modules)
    {
        ModuleControlContainer.Children.Clear();
        foreach (var netEnt in modules)
        {
            var ent = _ent.GetEntity(netEnt);
            var moduleSize = _ent.GetComponentOrNull<MechModuleComponent>(ent)?.Size ?? 1;
            var control = CreateEquipmentControl(ent, moduleSize);
            if (control == null)
                continue;

            control.OnRemoveButtonPressed += () => OnRemoveModuleButtonPressed?.Invoke(ent);
            ModuleControlContainer.AddChild(control);
        }
    }

    private MechEquipmentControl? CreateEquipmentControl(EntityUid ent, int? size = null)
    {
        var metaData = _ent.GetComponentOrNull<MetaDataComponent>(ent);
        if (metaData == null)
            return null;

        return new MechEquipmentControl(ent, metaData.EntityName, GetEquipmentUi(ent), size);
    }

    private Control? GetEquipmentUi(EntityUid ent)
    {
        if (_parentBui == null)
            return null;

        var uicomp = _ent.GetComponentOrNull<UIFragmentComponent>(ent);
        if (uicomp?.Ui == null)
            return null;

        uicomp.Ui.Setup(_parentBui, ent);
        return uicomp.Ui.GetUIFragmentRoot();
    }

    private IEntityManager EntityManager => _ent;

    private bool ContainerMatches(Control container, IReadOnlyList<NetEntity> entities)
    {
        return container.Children
            .OfType<MechEquipmentControl>()
            .Select(control => control.Entity)
            .SequenceEqual(entities.Select(EntityManager.GetEntity));
    }

    private int GetUsedModuleSize(IReadOnlyList<EntityUid> installed)
    {
        var usedModuleSize = 0;

        foreach (var installedModule in installed)
        {
            if (_ent.TryGetComponent<MechModuleComponent>(installedModule, out var module))
                usedModuleSize += module.Size;
        }

        return usedModuleSize;
    }

    private void UpdateLockControls(MechBoundUiState state)
    {
        LockControlsContainer.Visible = state.HasLock;
        if (!state.HasLock)
            return;

        LockStatusLabel.Text = Loc.GetString(state.IsLocked
            ? "mech-lock-status-locked"
            : "mech-lock-status-unlocked");

        UpdateLockButtonSet(
            DnaLockRegisterButton,
            DnaLockToggleButton,
            DnaLockResetButton,
            DnaLockInfoLabel,
            state.DnaLockRegistered,
            state.DnaLockActive,
            state.DnaLockOwner,
            "mech-lock-dna-info");

        UpdateLockButtonSet(
            CardLockRegisterButton,
            CardLockToggleButton,
            CardLockResetButton,
            CardLockInfoLabel,
            state.CardLockRegistered,
            state.CardLockActive,
            state.CardLockOwner,
            "mech-lock-card-info");
    }

    private void UpdateCabinControls(MechBoundUiState state)
    {
        CabinControlsContainer.Visible = state.CanAirtight || state.HasFanModule || state.HasGasModule;
        if (!CabinControlsContainer.Visible)
            return;

        AirtightToggleButton.Visible = state.CanAirtight;
        AirtightToggleButton.Pressed = state.IsAirtight;
        AirtightToggleButton.Text = Loc.GetString(state.IsAirtight
            ? "mech-airtight-enabled"
            : "mech-airtight-disabled");

        CabinPurgeButton.Visible = state.CanAirtight;
        CabinPurgeButton.Disabled = !state.CabinPurgeAvailable;

        if (state.CanAirtight)
        {
            var tempC = TemperatureHelpers.KelvinToCelsius(state.CabinTemperature);
            CabinPressureLabel.Text = Loc.GetString("mech-cabin-pressure-level",
                ("level", $"{state.CabinPressureLevel:F1}"));
            CabinTemperatureLabel.Text = Loc.GetString("mech-cabin-temperature-level",
                ("tempC", $"{tempC:F1}"));
            CabinPressureLabel.FontColorOverride = Color.White;
            CabinTemperatureLabel.FontColorOverride = Color.Orange;
        }
        else
        {
            CabinPressureLabel.Text = Loc.GetString("mech-no-airtight-status");
            CabinTemperatureLabel.Text = Loc.GetString("mech-no-airtight-status");
            CabinPressureLabel.FontColorOverride = Color.Gray;
            CabinTemperatureLabel.FontColorOverride = Color.Gray;
        }

        if (state.HasGasModule)
        {
            TankPressureLabel.Text = Loc.GetString("mech-tank-pressure-level",
                ("pressure", $"{state.TankPressure:F1}"),
                ("liters", $"{state.GasAmountLiters:F1}"));
            TankPressureLabel.FontColorOverride = Color.White;
        }
        else
        {
            TankPressureLabel.Text = Loc.GetString("mech-tank-missing");
            TankPressureLabel.FontColorOverride = Color.Gray;
        }

        FanToggleButton.Visible = state.HasFanModule;
        FilterToggleButton.Visible = state.HasFanModule;
        FanStateLabel.Visible = state.HasFanModule;

        FanToggleButton.Pressed = state.FanActive;
        FanToggleButton.Text = Loc.GetString(state.FanActive
            ? "mech-fan-enabled"
            : "mech-fan-disabled");

        FilterToggleButton.Pressed = state.FilterEnabled;
        FilterToggleButton.Text = Loc.GetString(state.FilterEnabled
            ? "mech-filter-enabled"
            : "mech-filter-disabled");

        FanStateLabel.Text = Loc.GetString($"mech-fan-state-{state.FanState.ToString().ToLowerInvariant()}");
    }

    private static void UpdateLockButtonSet(
        Button registerButton,
        Button toggleButton,
        Button resetButton,
        Label infoLabel,
        bool registered,
        bool active,
        string? owner,
        string infoLocale)
    {
        registerButton.Visible = !registered;
        toggleButton.Visible = registered;
        resetButton.Visible = registered;
        toggleButton.Text = Loc.GetString(active ? "mech-lock-deactivate" : "mech-lock-activate");

        infoLabel.Text = registered
            ? Loc.GetString(infoLocale, ("owner", owner ?? Loc.GetString("mech-lock-owner-unknown")))
            : Loc.GetString("mech-lock-not-registered");
    }
    // RS14-end
}
