// SPDX-FileCopyrightText: 2023 DrSmugleaf <DrSmugleaf@users.noreply.github.com>
// SPDX-FileCopyrightText: 2023 Visne <39844191+Visne@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 Nemanja <98561806+EmoGarbage404@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 Piras314 <p1r4s@proton.me>
// SPDX-FileCopyrightText: 2024 deltanedas <39013340+deltanedas@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 deltanedas <@deltanedas:kde.org>
// SPDX-FileCopyrightText: 2024 metalgearsloth <31366439+metalgearsloth@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 themias <89101928+themias@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 Aiden <28298836+Aidenkrz@users.noreply.github.com>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Client.UserInterface.Fragments;
using Content.Shared.Mech;
using Content.Shared.Mech.Components;
using Content.Shared.Mech.Equipment.Components;
using Content.Shared.Mech.Module.Components;
using Content.Shared.Temperature;
using Robust.Client.AutoGenerated;
using Robust.Client.Player;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Mech.Ui;

[GenerateTypedNameReferences]
public sealed partial class MechMenu : FancyWindow
{
    [Dependency] private readonly IEntityManager _ent = default!;
    [Dependency] private readonly IPlayerManager _player = default!;

    private EntityUid _mech;
    private BoundUserInterface? _parentBui;

    public event Action<EntityUid>? OnRemoveEquipmentButtonPressed;
    public event Action<EntityUid>? OnRemoveModuleButtonPressed;
    public event Action? OnDnaLockRegister;
    public event Action? OnDnaLockToggle;
    public event Action? OnDnaLockReset;
    public event Action? OnCardLockRegister;
    public event Action? OnCardLockToggle;
    public event Action? OnCardLockReset;
    public event Action? OnCabinPurge;
    public event Action<bool>? OnAirtightToggle;
    public event Action<bool>? OnFanToggle;
    public event Action<bool>? OnFilterToggle;

    public MechMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        AirtightButton.OnToggled += args => OnAirtightToggle?.Invoke(args.Pressed);
        CabinPurgeButton.OnPressed += _ => OnCabinPurge?.Invoke();
        FanToggle.StateChanged += isOn => OnFanToggle?.Invoke(isOn);
        FilterEnabledCheck.OnToggled += args => OnFilterToggle?.Invoke(args.Pressed);

        DnaLockRegisterButton.OnPressed += _ => OnDnaLockRegister?.Invoke();
        DnaLockBlockButton.OnPressed += _ => OnDnaLockToggle?.Invoke();
        DnaLockResetButton.OnPressed += _ => OnDnaLockReset?.Invoke();
        CardLockRegisterButton.OnPressed += _ => OnCardLockRegister?.Invoke();
        CardLockBlockButton.OnPressed += _ => OnCardLockToggle?.Invoke();
        CardLockResetButton.OnPressed += _ => OnCardLockReset?.Invoke();
    }

    public void SetEntity(EntityUid uid)
    {
        _mech = uid;
        MechView.SetEntity(uid);
        MechName.Text = _ent.GetComponent<MetaDataComponent>(uid).EntityName;
    }

    public void SetParentBui(BoundUserInterface parentBui)
    {
        _parentBui = parentBui;
    }

    public void UpdateState(MechBoundUiState state)
    {
        UpdateMechStats(state);
        UpdateMechControls(state);
        UpdateEquipmentView(state.Equipment, state.Modules);
        SetRemoveDisabledForContainer(EquipmentControlContainer, state.PilotPresent);
        SetRemoveDisabledForContainer(ModuleControlContainer, state.PilotPresent);
        RefreshEquipmentFragmentStates(state);
    }

    public void UpdateMechStats(MechBoundUiState state)
    {
        var integrityPercent = state.MaxIntegrity > 0f
            ? state.Integrity / state.MaxIntegrity
            : 0f;

        IntegrityDisplayBar.Value = integrityPercent;
        IntegrityDisplay.Text = Loc.GetString(state.IsBroken
            ? "mech-integrity-display-broken"
            : "mech-integrity-display", ("amount", (int) (integrityPercent * 100)));

        if (state.MaxEnergy > 0f)
        {
            var energyPercent = state.Energy / state.MaxEnergy;
            EnergyDisplayBar.Value = energyPercent;
            EnergyDisplay.Text = Loc.GetString("mech-energy-display", ("amount", (int) (energyPercent * 100)));
        }
        else
        {
            EnergyDisplayBar.Value = 0f;
            EnergyDisplay.Text = Loc.GetString("mech-energy-missing");
        }

        SlotDisplay.Text = Loc.GetString("mech-equipment-slot-display-label",
            ("used", state.EquipmentUsed),
            ("max", state.MaxEquipmentAmount));

        ModuleSlotDisplay.Text = Loc.GetString("mech-module-slot-display-label",
            ("used", state.ModuleSpaceUsed),
            ("max", state.ModuleSpaceMax));
    }

    private void UpdateMechControls(MechBoundUiState state)
    {
        FanToggle.Visible = state.HasFanModule;
        FilterEnabledCheck.Visible = state.HasFanModule;
        FanMissingLabel.Visible = !state.HasFanModule;

        CabinPurgeButton.Disabled = !state.CabinPurgeAvailable || !state.CanAirtight;
        AirtightButton.Visible = state.CanAirtight;
        CabinPurgeButton.Visible = state.CanAirtight;
        AirtightUnavailableLabel.Visible = !state.CanAirtight;

        if (AirtightButton.Pressed != state.IsAirtight)
            AirtightButton.Pressed = state.IsAirtight;

        if (state.HasFanModule)
        {
            if (FanToggle.IsOn != state.FanActive)
                FanToggle.IsOn = state.FanActive;

            if (FilterEnabledCheck.Pressed != state.FilterEnabled)
                FilterEnabledCheck.Pressed = state.FilterEnabled;
        }

        var tempC = TemperatureHelpers.KelvinToCelsius(state.CabinTemperature);

        if (state.CanAirtight)
        {
            CabinPressureLabel.Text = Loc.GetString("mech-cabin-pressure-level-label",
                ("level", $"{state.CabinPressureLevel:F1}"));
            CabinTemperatureLabel.Text = Loc.GetString("mech-cabin-temperature-level-label",
                ("tempC", $"{tempC:F1}"));
            CabinPressureLabel.FontColorOverride = Color.White;
            CabinTemperatureLabel.FontColorOverride = Color.Orange;
        }
        else
        {
            CabinPressureLabel.Text = Loc.GetString("mech-no-airtight-status-label");
            CabinTemperatureLabel.Text = Loc.GetString("mech-no-airtight-status-label");
            CabinPressureLabel.FontColorOverride = Color.Gray;
            CabinTemperatureLabel.FontColorOverride = Color.Gray;
        }

        if (state.HasGasModule)
        {
            TankPressureLabel.Text = Loc.GetString("mech-tank-pressure-level-label",
                ("state", "ok"),
                ("pressure", $"{state.TankPressure:F1}"));
            TankPressureLabel.FontColorOverride = Color.White;
        }
        else
        {
            TankPressureLabel.Text = Loc.GetString("mech-tank-pressure-level-label", ("state", "na"));
            TankPressureLabel.FontColorOverride = Color.Gray;
        }

        UpdateFanStatusDisplay(state.FanState);
        UpdateLockInfoLabels(state);
        UpdateLockButtons(state);
        SetAccessVisibility(state);
    }

    public void UpdateEquipmentView(IReadOnlyList<NetEntity> equipment, IReadOnlyList<NetEntity> modules)
    {
        if (!ContainerMatches(EquipmentControlContainer, equipment))
            RebuildEquipmentView(equipment);

        if (!ContainerMatches(ModuleControlContainer, modules))
            RebuildModuleView(modules);
    }

    private void RebuildEquipmentView(IReadOnlyList<NetEntity> equipment)
    {
        DetachEquipmentFragments(EquipmentControlContainer);
        EquipmentControlContainer.Children.Clear();
        foreach (var netEnt in equipment)
        {
            var ent = _ent.GetEntity(netEnt);
            var control = CreateEquipmentControl(ent, 1);
            if (control == null)
                continue;

            control.OnRemoveButtonPressed += () => OnRemoveEquipmentButtonPressed?.Invoke(ent);
            EquipmentControlContainer.AddChild(control);
        }
    }

    private void RebuildModuleView(IReadOnlyList<NetEntity> modules)
    {
        DetachEquipmentFragments(ModuleControlContainer);
        ModuleControlContainer.Children.Clear();
        foreach (var netEnt in modules)
        {
            var ent = _ent.GetEntity(netEnt);
            var size = _ent.GetComponentOrNull<MechModuleComponent>(ent)?.Size ?? 1;
            var control = CreateEquipmentControl(ent, size);
            if (control == null)
                continue;

            control.OnRemoveButtonPressed += () => OnRemoveModuleButtonPressed?.Invoke(ent);
            ModuleControlContainer.AddChild(control);
        }
    }

    private MechEquipmentControl? CreateEquipmentControl(EntityUid ent, int size)
    {
        var metaData = _ent.GetComponentOrNull<MetaDataComponent>(ent);
        if (metaData == null)
            return null;

        return new MechEquipmentControl(ent, metaData.EntityName, GetEquipmentUi(ent), size);
    }

    private static void DetachEquipmentFragments(Control container)
    {
        foreach (var control in container.Children.OfType<MechEquipmentControl>())
        {
            control.DetachFragment();
        }
    }

    private Control? GetEquipmentUi(EntityUid ent)
    {
        if (_parentBui == null)
            return null;

        var uicomp = _ent.GetComponentOrNull<UIFragmentComponent>(ent);
        if (uicomp?.Ui == null)
            return null;

        uicomp.Ui.Setup(_parentBui, ent);
        return uicomp.Ui.GetUIFragmentRoot();
    }

    private bool ContainerMatches(Control container, IReadOnlyList<NetEntity> entities)
    {
        return container.Children
            .OfType<MechEquipmentControl>()
            .Select(control => _ent.GetNetEntity(control.Entity))
            .SequenceEqual(entities);
    }

    private void RefreshEquipmentFragmentStates(MechBoundUiState state)
    {
        UpdateFragmentsForContainer(EquipmentControlContainer, state.EquipmentStates);
        UpdateFragmentsForContainer(ModuleControlContainer, state.EquipmentStates);
    }

    private void UpdateFragmentsForContainer(Control container, Dictionary<NetEntity, BoundUserInterfaceState> states)
    {
        foreach (var control in container.Children.OfType<MechEquipmentControl>())
        {
            var netEnt = _ent.GetNetEntity(control.Entity);
            if (!states.TryGetValue(netEnt, out var eqState))
                continue;

            var uicomp = _ent.GetComponentOrNull<UIFragmentComponent>(control.Entity);
            uicomp?.Ui?.UpdateState(eqState);
        }
    }

    private void UpdateFanStatusDisplay(MechFanState fanState)
    {
        var stateKey = fanState switch
        {
            MechFanState.Off => "off",
            MechFanState.On => "on",
            MechFanState.Idle => "idle",
            _ => "na"
        };
        var stateColor = fanState switch
        {
            MechFanState.Off => Color.Red,
            MechFanState.On => Color.Green,
            MechFanState.Idle => Color.Yellow,
            _ => Color.Gray
        };

        FanStatusLabel.Text = Loc.GetString("mech-fan-status-level-label", ("state", stateKey));
        FanStatusLabel.FontColorOverride = stateColor;
    }

    private static void SetRemoveDisabledForContainer(Control container, bool disabled)
    {
        foreach (var control in container.Children.OfType<MechEquipmentControl>())
        {
            control.SetRemoveDisabled(disabled);
        }
    }

    private void UpdateLockInfoLabels(MechBoundUiState state)
    {
        DnaLockInfoLabel.Text = GetLockOwnerText(state.DnaLockRegistered, state.DnaLockOwner);
        CardLockInfoLabel.Text = GetLockOwnerText(state.CardLockRegistered, state.CardLockOwner);
    }

    private static string GetLockOwnerText(bool registered, string? owner)
    {
        if (!registered)
            return Loc.GetString("mech-lock-not-set-label");

        return $"[{(string.IsNullOrEmpty(owner) ? Loc.GetString("mech-lock-owner-unknown") : owner)}]";
    }

    private void UpdateLockButtons(MechBoundUiState state)
    {
        UpdateLockButtonSet(DnaLockRegisterButton, DnaLockBlockButton, DnaLockResetButton,
            state.DnaLockRegistered, state.DnaLockActive);
        UpdateLockButtonSet(CardLockRegisterButton, CardLockBlockButton, CardLockResetButton,
            state.CardLockRegistered, state.CardLockActive);
    }

    private static void UpdateLockButtonSet(
        Button registerButton,
        Button blockButton,
        Button resetButton,
        bool registered,
        bool active)
    {
        registerButton.Visible = !registered;
        blockButton.Visible = registered;
        resetButton.Visible = registered;
        blockButton.Text = Loc.GetString(active ? "mech-lock-deactivate-button" : "mech-lock-activate-button");
        blockButton.Pressed = active;
    }

    private void SetAccessVisibility(MechBoundUiState state)
    {
        var user = _player.LocalEntity;
        if (user == null || !state.HasLock)
        {
            HaveAccessEquipment.Visible = true;
            HaveAccessSettings.Visible = true;
            NoAccessSettings.Visible = false;
            NoAccessEquipment.Visible = false;
            return;
        }

        var lockSystem = _ent.System<MechLockSystem>();
        var noAccess = state.IsLocked && !lockSystem.CheckAccess(_mech, user.Value);
        HaveAccessEquipment.Visible = !noAccess;
        HaveAccessSettings.Visible = !noAccess;
        NoAccessSettings.Visible = noAccess;
        NoAccessEquipment.Visible = noAccess;
    }
}
