// SPDX-FileCopyrightText: 2022 Nemanja <98561806+EmoGarbage404@users.noreply.github.com>
// SPDX-FileCopyrightText: 2023 Visne <39844191+Visne@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 Piras314 <p1r4s@proton.me>
// SPDX-FileCopyrightText: 2025 Aiden <28298836+Aidenkrz@users.noreply.github.com>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Client.Items;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Mech.Ui;

[GenerateTypedNameReferences]
public sealed partial class MechEquipmentControl : Control
{
    [Dependency] private readonly IEntityManager _entMan = default!;

    public EntityUid Entity { get; }

    public event Action? OnRemoveButtonPressed;

    public MechEquipmentControl(EntityUid entity, string itemName, Control? fragment, int? size = null)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        Entity = entity;
        SetContent(itemName, fragment, size);
        EquipmentView.SetEntity(entity);
        RemoveButton.TexturePath = "/Textures/Interface/Nano/cross.svg.png";
        SetRemoveDisabled(true);

        RemoveButton.OnPressed += _ => OnRemoveButtonPressed?.Invoke();
    }

    public void SetRemoveDisabled(bool disabled)
    {
        RemoveButton.Disabled = disabled;
        RemoveButton.ToolTip = disabled
            ? Loc.GetString("mech-remove-disabled-tooltip")
            : null;

        RemoveButton.Modulate = disabled
            ? new Color(0.5f, 0.5f, 0.5f, 1f)
            : Color.White;
    }

    private void SetContent(string itemName, Control? fragment, int? size)
    {
        EquipmentName.SetMessage(itemName);
        EquipmentSize.Text = size == null
            ? string.Empty
            : $"[{size.Value}]"; // RS14: Match upstream compact equipment size display.
        EquipmentSize.Visible = size != null;

        var showContainer = false;
        if (fragment is { Disposed: false })
        {
            showContainer = true;
            AddChildWithMargins(fragment);
        }

        var status = new ItemStatusCollectMessage();
        _entMan.EventBus.RaiseLocalEvent(Entity, status);
        foreach (var control in status.Controls)
        {
            showContainer = true;
            AddChildWithMargins(control);
        }

        CustomControlContainer.Visible = showContainer;
        Separator.Visible = showContainer;
    }

    private void AddChildWithMargins(Control child)
    {
        child.Margin = new Thickness(3);
        CustomControlContainer.AddChild(child);
    }

    public void DetachFragment()
    {
        CustomControlContainer.RemoveAllChildren();
    }
}
