// SPDX-FileCopyrightText: 2023 DrSmugleaf <DrSmugleaf@users.noreply.github.com>
// SPDX-FileCopyrightText: 2023 Visne <39844191+Visne@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 Nemanja <98561806+EmoGarbage404@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 Piras314 <p1r4s@proton.me>
// SPDX-FileCopyrightText: 2024 deltanedas <39013340+deltanedas@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 deltanedas <@deltanedas:kde.org>
// SPDX-FileCopyrightText: 2024 metalgearsloth <31366439+metalgearsloth@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 themias <89101928+themias@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 Aiden <28298836+Aidenkrz@users.noreply.github.com>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Client.UserInterface.Fragments;
using Content.Shared.Mech;
using Content.Shared.Mech.Components;
using Content.Shared.Mech.Module.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Mech.Ui;

[GenerateTypedNameReferences]
public sealed partial class MechMenu : FancyWindow
{
    [Dependency] private readonly IEntityManager _ent = default!;

    private EntityUid _mech;
    private BoundUserInterface? _parentBui;

    public event Action<EntityUid>? OnRemoveEquipmentButtonPressed;
    // RS14-start
    public event Action<EntityUid>? OnRemoveModuleButtonPressed;
    public event Action? OnDnaLockRegister;
    public event Action? OnDnaLockToggle;
    public event Action? OnDnaLockReset;
    public event Action? OnCardLockRegister;
    public event Action? OnCardLockToggle;
    public event Action? OnCardLockReset;
    // RS14-end

    public MechMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        // RS14-start
        DnaLockRegisterButton.OnPressed += _ => OnDnaLockRegister?.Invoke();
        DnaLockToggleButton.OnPressed += _ => OnDnaLockToggle?.Invoke();
        DnaLockResetButton.OnPressed += _ => OnDnaLockReset?.Invoke();
        CardLockRegisterButton.OnPressed += _ => OnCardLockRegister?.Invoke();
        CardLockToggleButton.OnPressed += _ => OnCardLockToggle?.Invoke();
        CardLockResetButton.OnPressed += _ => OnCardLockReset?.Invoke();
        // RS14-end
    }

    public void SetEntity(EntityUid uid)
    {
        MechView.SetEntity(uid);
        _mech = uid;
    }

    public void SetParentBui(BoundUserInterface parentBui)
    {
        _parentBui = parentBui;
    }

    public void UpdateMechStats(MechBoundUiState state)
    {
        if (!_ent.TryGetComponent<MechComponent>(_mech, out var mechComp))
            return;

        var integrityPercent = mechComp.Integrity / mechComp.MaxIntegrity;
        IntegrityDisplayBar.Value = integrityPercent.Float();
        IntegrityDisplay.Text = Loc.GetString("mech-integrity-display", ("amount", (integrityPercent*100).Int()));

        if (mechComp.MaxEnergy != 0f)
        {
            var energyPercent = mechComp.Energy / mechComp.MaxEnergy;
            EnergyDisplayBar.Value = energyPercent.Float();
            EnergyDisplay.Text = Loc.GetString("mech-energy-display", ("amount", (energyPercent*100).Int()));
        }
        else
        {
            EnergyDisplayBar.Value = 0f;
            EnergyDisplay.Text = Loc.GetString("mech-energy-missing");
        }

        SlotDisplay.Text = Loc.GetString("mech-slot-display",
            ("amount", mechComp.MaxEquipmentAmount - mechComp.EquipmentContainer.ContainedEntities.Count));

        var usedModuleSize = GetUsedModuleSize(mechComp.ModuleContainer.ContainedEntities);
        ModuleSlotDisplay.Text = Loc.GetString("mech-module-slot-display",
            ("amount", mechComp.MaxModuleAmount - usedModuleSize));

        UpdateLockControls(state);
    }

    public void UpdateEquipmentView()
    {
        if (!_ent.TryGetComponent<MechComponent>(_mech, out var mechComp))
            return;

        if (!ContainerMatches(EquipmentControlContainer, mechComp.EquipmentContainer.ContainedEntities))
            RebuildEquipmentView(mechComp.EquipmentContainer.ContainedEntities);

        // RS14-start
        if (!ContainerMatches(ModuleControlContainer, mechComp.ModuleContainer.ContainedEntities))
            RebuildModuleView(mechComp.ModuleContainer.ContainedEntities);
        // RS14-end
    }

    private void RebuildEquipmentView(IReadOnlyList<EntityUid> equipment)
    {
        EquipmentControlContainer.Children.Clear();
        foreach (var ent in equipment)
        {
            if (!_ent.TryGetComponent<MetaDataComponent>(ent, out var metaData))
                continue;

            var control = new MechEquipmentControl(ent, metaData.EntityName, GetEquipmentUi(ent));

            control.OnRemoveButtonPressed += () => OnRemoveEquipmentButtonPressed?.Invoke(ent);

            EquipmentControlContainer.AddChild(control);
        }
    }

    // RS14-start
    private void RebuildModuleView(IReadOnlyList<EntityUid> modules)
    {
        ModuleControlContainer.Children.Clear();
        foreach (var ent in modules)
        {
            if (!_ent.TryGetComponent<MetaDataComponent>(ent, out var metaData))
                continue;

            var moduleSize = _ent.TryGetComponent<MechModuleComponent>(ent, out var module)
                ? module.Size
                : 1;

            var control = new MechEquipmentControl(ent, metaData.EntityName, GetEquipmentUi(ent), moduleSize);

            control.OnRemoveButtonPressed += () => OnRemoveModuleButtonPressed?.Invoke(ent);

            ModuleControlContainer.AddChild(control);
        }
    }

    private Control? GetEquipmentUi(EntityUid ent)
    {
        if (_parentBui == null)
            return null;

        var uicomp = _ent.GetComponentOrNull<UIFragmentComponent>(ent);
        if (uicomp?.Ui == null)
            return null;

        uicomp.Ui.Setup(_parentBui, ent);
        return uicomp.Ui.GetUIFragmentRoot();
    }

    private static bool ContainerMatches(Control container, IReadOnlyList<EntityUid> entities)
    {
        return container.Children
            .OfType<MechEquipmentControl>()
            .Select(control => control.Entity)
            .SequenceEqual(entities);
    }

    private int GetUsedModuleSize(IReadOnlyList<EntityUid> installed)
    {
        var usedModuleSize = 0;

        foreach (var installedModule in installed)
        {
            if (_ent.TryGetComponent<MechModuleComponent>(installedModule, out var module))
                usedModuleSize += module.Size;
        }

        return usedModuleSize;
    }

    private void UpdateLockControls(MechBoundUiState state)
    {
        LockControlsContainer.Visible = state.HasLock;
        if (!state.HasLock)
            return;

        LockStatusLabel.Text = Loc.GetString(state.IsLocked
            ? "mech-lock-status-locked"
            : "mech-lock-status-unlocked");

        UpdateLockButtonSet(
            DnaLockRegisterButton,
            DnaLockToggleButton,
            DnaLockResetButton,
            DnaLockInfoLabel,
            state.DnaLockRegistered,
            state.DnaLockActive,
            state.DnaLockOwner,
            "mech-lock-dna-info");

        UpdateLockButtonSet(
            CardLockRegisterButton,
            CardLockToggleButton,
            CardLockResetButton,
            CardLockInfoLabel,
            state.CardLockRegistered,
            state.CardLockActive,
            state.CardLockOwner,
            "mech-lock-card-info");
    }

    private static void UpdateLockButtonSet(
        Button registerButton,
        Button toggleButton,
        Button resetButton,
        Label infoLabel,
        bool registered,
        bool active,
        string? owner,
        string infoLocale)
    {
        registerButton.Visible = !registered;
        toggleButton.Visible = registered;
        resetButton.Visible = registered;
        toggleButton.Text = Loc.GetString(active ? "mech-lock-deactivate" : "mech-lock-activate");

        infoLabel.Text = registered
            ? Loc.GetString(infoLocale, ("owner", owner ?? Loc.GetString("mech-lock-owner-unknown")))
            : Loc.GetString("mech-lock-not-registered");
    }
    // RS14-end
}
