# SPDX-FileCopyrightText: 2024 Piras314 <92357316+Piras314@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 Aiden <28298836+Aidenkrz@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 Aiden <aiden@djkraz.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later
# From https://github.com/DeltaV-Station/Delta-v/
name: PR Changelogs
concurrency: commit_action
on:
  pull_request_target:
    types: [closed]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CHANGELOG_DIR: ${{ vars.CHANGELOG_DIR }}
  PR_NUMBER: ${{ github.event.number }}

jobs:
  changelog:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    permissions:
      contents: write
    steps:
      - name: Checkout Master
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: "${{ vars.CHANGELOG_BRANCH }}"

      - name: Setup Git
        run: |
          git config --global user.name "${{ vars.CHANGELOG_USER }}"
          git config --global user.email "${{ vars.CHANGELOG_EMAIL }}"
        shell: bash

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install Dependencies
        run: |
          cd "Tools/changelog"
          npm install
        shell: bash
        continue-on-error: true

      - name: Generate Changelog
        run: |
          cd "Tools/changelog"
          node changelog.js
        shell: bash
        continue-on-error: true

      - name: Commit Changelog
        run: |
          git add *.yml
          git commit -m "${{ vars.CHANGELOG_MESSAGE }} (#${{ env.PR_NUMBER }})"
          git push
        shell: bash
        continue-on-error: true

      - name: Prepare Discord Description
        id: prep_discord
        shell: bash
        env:
          PR_BODY: ${{ github.event.pull_request.body }}
        run: |
          BODY="$PR_BODY"

          BODY_CLEAN=$(echo "$BODY" | sed 's/<!--.*-->//g' | sed '/<!--/,/-->/d')

          if [[ "$BODY_CLEAN" == *":cl:"* ]]; then
            CL_BLOCK=$(echo "$BODY_CLEAN" | sed -n '/:cl:/,$p' | sed '1d')

            FINAL_TEXT=$(echo "$CL_BLOCK" | \
              sed 's/^[[:space:]]*- Добавлено:[[:space:]]*/\n➕ **Добавлено**\n• /g' | \
              sed 's/^[[:space:]]*- Исправлено:[[:space:]]*/\n🐛 **Исправлено**\n• /g' | \
              sed 's/^[[:space:]]*- Изменено:[[:space:]]*/\n🔧 **Изменено**\n• /g' | \
              sed 's/^[[:space:]]*- Удалено:[[:space:]]*/\n➖ **Удалено**\n• /g' | \
              sed 's/^[[:space:]]*- add:[[:space:]]*/\n➕ **Добавлено**\n• /g' | \
              sed 's/^[[:space:]]*- fix:[[:space:]]*/\n🐛 **Исправлено**\n• /g' | \
              sed 's/^[[:space:]]*- tweak:[[:space:]]*/\n🔧 **Изменено**\n• /g' | \
              sed 's/^[[:space:]]*- remove:[[:space:]]*/\n➖ **Удалено**\n• /g')

            FINAL_TEXT=$(echo "$FINAL_TEXT" | sed '/^[[:space:]]*$/d')
            
            echo "CLEAN_BODY<<EOF" >> $GITHUB_ENV
            echo "$FINAL_TEXT" >> $GITHUB_ENV
            echo "EOF" >> $GITHUB_ENV
          else
            echo "CLEAN_BODY=Изменения не указаны." >> $GITHUB_ENV
          fi

      - name: Send Changelog to Discord
        uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
          title: "${{ github.event.pull_request.title }}"
          description: |
            **Список изменений из PR #${{ env.PR_NUMBER }}**
            ${{ env.CLEAN_BODY }}
          color: bf0000
          footer: "Автор: ${{ github.event.pull_request.user.login }} • PR #${{ env.PR_NUMBER }} • ${{ github.event.pull_request.merged_at }}"
