# SPDX-License-Identifier: AGPL-3.0-or-later

name: Publish

concurrency:
  group: publish
  cancel-in-progress: true

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          submodules: 'recursive'

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4.1.0
        with:
          dotnet-version: 9.0.x
        env:
          DOTNET_INSTALL_DIR: ${{ runner.temp }}/.dotnet

      - name: Set DOTNET_ROOT and PATH
        run: |
          echo "DOTNET_ROOT=${{ runner.temp }}/.dotnet" >> $GITHUB_ENV
          echo "${{ runner.temp }}/.dotnet" >> $GITHUB_PATH

      - name: Check .NET installation
        run: dotnet --info

      - name: Fetch engine tags
        run: |
          cd RobustToolbox
          git fetch --tags --force

      - name: Restore dependencies
        run: dotnet restore

      - name: Build packaging
        run: dotnet build Content.Packaging --configuration Release --no-restore /m

      - name: Package server
        run: dotnet run --project Content.Packaging server --platform linux-x64

      - name: Package client
        run: dotnet run --project Content.Packaging client --no-wipe-release

      - name: Publish version to Robust.Cdn
        run: Tools/publish_multi_request.py
        env:
          PUBLISH_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
          GITHUB_SHA: ${{ github.sha }}
          FORK_ID: ${{ vars.FORK_ID }}
          ROBUST_CDN_URL: ${{ vars.ROBUST_CDN_URL }}
